### ISSUE TITLE
Fixing the difficulty of re-highlighting the same portion of text to add a new annotation

### ISSUE THREAD

**Issue by miahass** [edgeryders/annotator_store-gem#168] opened 2020-07-31 11:03 UTC
In lieu of this, then fixing the difficulty of re-highlighting the same portion of text to add a new annotation is needed. I add the important because it's currently a frustration echoed by all of the ethnographers that creates frustration at high frequency every time they assign a code --- so I'm marking this as important because it's a high priority to do one or the other as soon as possible.

_Originally posted by @miahass in https://github.com/edgeryders/annotator_store-gem/issues/60#issuecomment-667064469_

**Comment by miahass** [comment] 2020-07-31 11:05
When highlighting and adding codes, once a certain number of codes are added (I think 3?) to the same highlighted portion of text, it becomes hard to add more (when you highlight, you just see the codes already assigned). The right click fix doesn't work all the time, and it makes coding erratic-- workaround has been highlighting slightly different portions of text, but this still creates issues sometimes if you don't do it perfectly. Ideal fix is multiple annotations to one part of text at a time, but if not possible then fixing this function would be an improvement.

**Comment by tanius** [comment] 2020-08-01 21:53
Closing as duplicate of #104 . Also because "ideal fix is multiple annotations to one part of text at a time" and that ideal fix seems simpler than wading through the low-level JavaScript madness, we'll attempt the low-level fix (managed in #60).

**Closed by tanius** 2020-08-01 21:53 UTC
