### ISSUE TITLE
Destroy codes from the edit or view tab. 

### ISSUE THREAD

**Issue by skoteskote** [edgeryders/annotator_store-gem#180] opened 2020-08-26 08:37 UTC
Now I need to search for a code to delete it, which is a bit time consuming when doing code cleaning.

**Comment by tanius** [comment] 2020-08-26 09:57
Duplicate of #125. Added #125 to the [UX Initiative milestone](https://github.com/edgeryders/annotator_store-gem/milestone/1), so we'll prioritize it over other issues.

**Closed by tanius** 2020-08-26 09:57 UTC
